// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Manually define the Database type as a workaround for the generation issue
export type Database = {
  renotimeline_schema: any;
  shared_schema: any;
  calcreno_schema: any;
  public: any;
};

const SUPABASE_URL = "https://kralcmyhjvoiywcpntkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyYWxjbXloanZvaXl3Y3BudGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzM3OTAsImV4cCI6MjA3MTQ0OTc5MH0.10JbU5SR2bwJyGorKifCVqCqQcnbBR4xup7NnYxz3AE";

const commonOptions = {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
    flowType: 'pkce' as const,
  },
  global: {
    headers: { 'x-realtime-revalidate': 'true' },
  },
};

// Create the main client first
const mainClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, commonOptions);

/**
 * Creates a schema-specific client that shares auth with mainClient.
 * Note: This creates a new client instance but reassigns auth to prevent
 * multiple auth state. Each client targets a different PostgreSQL schema.
 * For production optimization, consider lazy loading clients on demand.
 */
const createSchemaClientWithSharedAuth = (schema: keyof Database) => {
  const client = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    ...commonOptions,
    db: {
      schema,
    },
  });
  
  // Share the auth instance from the main client
  (client as any).auth = mainClient.auth;
  
  return client;
};

// Default client for RenoTimeline app data
export const supabase = mainClient;
export const renotimelineClient = createSchemaClientWithSharedAuth('renotimeline_schema');

// Client for shared schema (user profiles, etc.)
export const sharedClient = createSchemaClientWithSharedAuth('shared_schema');

// Client for CalcReno schema (for project imports)
export const calcrenoClient = createSchemaClientWithSharedAuth('calcreno_schema');

// Client for the default public schema
export const publicClient = createSchemaClientWithSharedAuth('public');