// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Manually define the Database type as a workaround for the generation issue
export type Database = {
  renotimeline_schema: any;
  shared_schema: any;
  calcreno_schema: any;
  public: any;
};

const SUPABASE_URL = "https://kralcmyhjvoiywcpntkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyYWxjbXloanZvaXl3Y3BudGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzM3OTAsImV4cCI6MjA3MTQ0OTc5MH0.10JbU5SR2bwJyGorKifCVqCqQcnbBR4xup7NnYxz3AE";

const commonOptions = {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
    flowType: 'pkce' as const,
  },
  global: {
    headers: { 'x-realtime-revalidate': 'true' },
  },
};

// Create the main client first
const mainClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, commonOptions);

/**
 * Creates a schema-specific client that shares auth with mainClient.
 * Uses lazy initialization to avoid creating multiple GoTrueClient instances.
 * Schema clients don't persist sessions - they share the main client's auth.
 */
const createSchemaClientWithSharedAuth = (schema: keyof Database) => {
  const client = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      autoRefreshToken: false, // Main client handles this
      persistSession: false,   // Main client handles this
      detectSessionInUrl: false,
      flowType: 'pkce' as const,
    },
    db: {
      schema,
    },
    global: {
      headers: { 'x-realtime-revalidate': 'true' },
    },
  });

  // Share the auth instance from the main client
  (client as any).auth = mainClient.auth;

  return client;
};

// Lazy initialization to prevent multiple GoTrueClient warnings
let _renotimelineClient: ReturnType<typeof createClient> | null = null;
let _sharedClient: ReturnType<typeof createClient> | null = null;
let _calcrenoClient: ReturnType<typeof createClient> | null = null;
let _publicClient: ReturnType<typeof createClient> | null = null;

// Default client for RenoTimeline app data
export const supabase = mainClient;

export const renotimelineClient = new Proxy({} as ReturnType<typeof createClient>, {
  get(target, prop) {
    if (!_renotimelineClient) {
      _renotimelineClient = createSchemaClientWithSharedAuth('renotimeline_schema');
    }
    return (_renotimelineClient as any)[prop];
  }
});

// Client for shared schema (user profiles, etc.)
export const sharedClient = new Proxy({} as ReturnType<typeof createClient>, {
  get(target, prop) {
    if (!_sharedClient) {
      _sharedClient = createSchemaClientWithSharedAuth('shared_schema');
    }
    return (_sharedClient as any)[prop];
  }
});

// Client for CalcReno schema (for project imports)
export const calcrenoClient = new Proxy({} as ReturnType<typeof createClient>, {
  get(target, prop) {
    if (!_calcrenoClient) {
      _calcrenoClient = createSchemaClientWithSharedAuth('calcreno_schema');
    }
    return (_calcrenoClient as any)[prop];
  }
});

// Client for the default public schema
export const publicClient = new Proxy({} as ReturnType<typeof createClient>, {
  get(target, prop) {
    if (!_publicClient) {
      _publicClient = createSchemaClientWithSharedAuth('public');
    }
    return (_publicClient as any)[prop];
  }
});